language: php

sudo: false

env:
  global:
    - DB=MYSQL CORE_RELEASE=3.1

matrix:
  include:
    - php: 5.6
      env: DB=MYSQL
    - php: 5.5
      env: DB=MYSQL
    - php: 5.4
      env: DB=MYSQL
    - php: 5.3
      env: DB=MYSQL


before_script:
  - phpenv rehash
  - composer self-update || true
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss

script:
  - vendor/bin/phpunit lumberjack/tests/
