---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'simple'

Member:
  extensions:
    - MemberExtension
    - ReferralMember_Extension

SiteConfig:
  extensions:
    - SiteConfig_Extension
    - ReferralSetting

Page:
  extensions:
    - 'AdvancedWidgetPageExtension'

Blog:
  extensions:
    - Blog_Extension
BlogPost:
  extensions:
    - BlogPost_Extension

Currency:
  currency_symbol: '&#163;'

PaymentProcessor:
    supported_methods:
        dev:
            - 'StripePaymentGateway'
        live:
            - 'StripePaymentGateway'

StripeGateway:
    test_api_secret: "sk_test_h2HmvDNkMDOyQWOFgtk6IMaS"
    api_secret: "sk_live_kcLqvPTYnCUSJ0q2IsVC0i6A"