---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'simple'

Member:
  extensions:
    - MemberExtension
    - ReferralMember_Extension

SiteConfig:
  extensions:
    - ReferralSetting

Page:
  extensions:
    - 'AdvancedWidgetPageExtension'

Blog:
  extensions:
    - Blog_Extension
BlogPost:
  extensions:
    - BlogPost_Extension